---
title: "Rozdział 10	Optymalizacja wykorzystania zasóbów komputera - praca z dużą ilością danych"
output:
  word_document: default
  html_document:
    df_print: paged
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
1. Bibliotek ___ff___
```{r otwieranie pliku funkcją z biblioteki ff}

library(ff)
system.time(dane1 <- read.csv.ffdf(file="./Dane/13 - bigdata.txt",sep=" "))
memory.size()

```
2. Biblioteka ___bigmemory___

```{r otwieranie pliku funkcją z biblioteki bigmemory}
library (bigmemory)
library (biganalytics)
system.time(dane2<-read.big.matrix("./Dane/13 - bigdata.txt",header = F,type = "integer",sep =" ",
                                   backingfile = "bigdata.bin", descriptor = "bigdata.desc",
                                   shared=TRUE))
memory.size()
# informacje doyczące danych
describe(dane2)
# przykładowa operacja, czyli dane są traktowane jak zwykły obiekt R
system.time(print(summary(dane1[,1])))
system.time(print(summary(dane2[,1])))

```





